name: 9ui
favicon: null
layout_spectrum: 0.75877
typography_spectrum: 0.54179
title: 9ui
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#363532'
    - '#fdad29'
    - '#919191'
    - '#d72115'
  brandStrength: 1
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
