name: 9ui
favicon: null
layout_spectrum: 0.75877
typography_spectrum: 0.54179
title: 9ui
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcc00'
    - '#484743'
    - '#d0aa10'
    - '#84732c'
    - '#a88d1f'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
