name: 9ui
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53678
title: 9ui
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#363532'
    - '#ffba00'
    - '#000000'
    - '#a8750f'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
